# Generated by Django 5.1.7 on 2025-04-04 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_add',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Address', models.TextField()),
                ('Job_title', models.CharField(max_length=50)),
                ('Department', models.CharField(max_length=50)),
                ('Employee_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=10)),
                ('Salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Date_hired', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='employee_pics/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
