# Generated by Django 5.1.7 on 2025-04-14 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_add', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='post_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_department', models.CharField(choices=[('Management', 'Management'), ('HR', 'HR'), ('IT', 'IT'), ('Sales', 'Sales'), ('Marketing', 'Marketing'), ('Finance', 'Finance'), ('Customer Service', 'Customer Service'), ('Operations', 'Operations'), ('Research', 'Research'), ('Design', 'Design'), ('Development', 'Development'), ('QA', 'QA'), ('Support', 'Support'), ('Other', 'Other')], max_length=50)),
                ('job_title', models.CharField(choices=[('Software Engineer', 'Software Engineer'), ('Web Developer', 'Web Developer'), ('UI/UX Designer', 'UI/UX Designer'), ('Project Manager', 'Project Manager'), ('Product Manager', 'Product Manager'), ('HR Manager', 'HR Manager'), ('IT Manager', 'IT Manager'), ('Sales Manager', 'Sales Manager'), ('Marketing Manager', 'Marketing Manager'), ('Finance Manager', 'Finance Manager'), ('Customer Service Manager', 'Customer Service Manager'), ('Operations Manager', 'Operations Manager'), ('Research Manager', 'Research Manager'), ('Design Manager', 'Design Manager'), ('Development Manager', 'Development Manager'), ('QA Manager', 'QA Manager'), ('Support Manager', 'Support Manager'), ('Other', 'Other')], max_length=50)),
                ('job_position', models.CharField(choices=[('Mid level', 'Mid level'), ('Senior level', 'Senior level'), ('Junior level', 'Junior level'), ('Intern', 'Intern'), ('Manager', 'Manager'), ('Supervisor', 'Supervisor'), ('Staff', 'Staff'), ('Lead', 'Lead'), ('Specialist', 'Specialist'), ('Analyst', 'Analyst'), ('Designer', 'Designer'), ('Developer', 'Developer'), ('Engineer', 'Engineer'), ('Expert', 'Expert'), ('Consultant', 'Consultant'), ('Other', 'Other')], max_length=50)),
                ('job_experience', models.IntegerField()),
                ('job_education', models.CharField(choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Doctorate', 'Doctorate'), ('Diploma', 'Diploma'), ('Certificate', 'Certificate'), ('Associate', 'Associate'), ('High School', 'High School'), ('Vocational', 'Vocational'), ('Other', 'Other')], max_length=50)),
                ('job_skills', models.CharField(choices=[('Python', 'Python'), ('Java', 'Java'), ('C++', 'C++'), ('JavaScript', 'JavaScript'), ('SQL', 'SQL'), ('C#', 'C#'), ('PHP', 'PHP'), ('Ruby', 'Ruby'), ('Swift', 'Swift'), ('Kotlin', 'Kotlin'), ('Go', 'Go'), ('C', 'C'), ('Other', 'Other')], max_length=50)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(choices=[('Remote', 'Remote'), ('Onsite', 'Onsite'), ('Hybrid', 'Hybrid')], max_length=50)),
                ('job_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_type', models.CharField(choices=[('Full time', 'Full time'), ('Part time', 'Part time'), ('Contract', 'Contract'), ('Intern', 'Intern')], max_length=10)),
                ('job_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Closed', 'Closed')], max_length=10)),
                ('job_created_at', models.DateField(auto_now_add=True)),
                ('job_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='employee_add',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Employee_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField()),
                ('attendance_status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('Leave', 'Leave')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_add.employee_add')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField()),
                ('leave_type', models.CharField(choices=[('Annual', 'Annual'), ('Medical', 'Medical'), ('Other', 'Other')], max_length=10)),
                ('leave_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_add.employee_add')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance_date', models.DateField()),
                ('performance_rating', models.CharField(choices=[('Excellent', 'Excellent'), ('Good', 'Good'), ('Average', 'Average')], max_length=10)),
                ('performance_feedback', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_add.employee_add')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField()),
                ('salary_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid')], max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_add.employee_add')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_date', models.DateField()),
                ('training_type', models.CharField(choices=[('Technical', 'Technical'), ('Soft skills', 'Soft skills'), ('Other', 'Other')], max_length=20)),
                ('training_feedback', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_add.employee_add')),
            ],
        ),
        migrations.CreateModel(
            name='job_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('application_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=10)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_add.employee_add')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_add.post_job')),
            ],
        ),
        migrations.CreateModel(
            name='job_interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_location', models.CharField(max_length=50)),
                ('interview_feedback', models.TextField()),
                ('interview_result', models.CharField(choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('On hold', 'On hold')], max_length=10)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_add.job_application')),
            ],
        ),
    ]
