# Generated by Django 5.2 on 2025-05-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_add', '0002_alter_post_job_job_max_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_job',
            name='post_app',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post_job',
            name='quota',
            field=models.IntegerField(null=True),
        ),
    ]
