# Generated by Django 5.1.7 on 2025-04-14 09:48

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_add', '0002_post_job_employee_add_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_job',
            name='job_updated_at',
        ),
        migrations.AlterField(
            model_name='post_job',
            name='job_department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='job_description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='job_education',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='job_location',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='job_position',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='job_skills',
            field=multiselectfield.db.fields.MultiSelectField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='job_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='job_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='post_job',
            name='job_type',
            field=models.CharField(max_length=10),
        ),
    ]
