# Generated by Django 5.2 on 2025-05-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_add', '0003_post_job_post_app_post_job_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_job',
            name='post_app',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
